set_property PACKAGE_PIN E3 [get_ports user_lnk_up_0]
set_property IOSTANDARD LVCMOS33 [get_ports user_lnk_up_0]

set_property PACKAGE_PIN AB12 [get_ports {diff_clock_rtl_0_clk_p[0]}]
set_property PACKAGE_PIN V12 [get_ports {diff_clock_rtl_1_clk_p[0]}]
set_property PACKAGE_PIN E2 [get_ports {user_lnk_up_1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {user_lnk_up_1[0]}]
set_property PACKAGE_PIN B3 [get_ports {M2_1_PERSTn[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M2_1_PERSTn[0]}]
set_property PACKAGE_PIN A3 [get_ports {M2_2_PERSTn[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M2_2_PERSTn[0]}]
set_property PACKAGE_PIN D4 [get_ports {M2_1_DET[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M2_1_DET[0]}]
set_property PACKAGE_PIN D3 [get_ports {M2_2_DET[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M2_2_DET[0]}]

set_property DRIVE 12 [get_ports {M2_1_PERSTn[0]}]

set_property PACKAGE_PIN D2 [get_ports {M2_1_V33_EN[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M2_1_V33_EN[0]}]
set_property PACKAGE_PIN C1 [get_ports {M2_2_V33_EN[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M2_2_V33_EN[0]}]

set_property PACKAGE_PIN AD4 [get_ports {pcie_7x_mgt_rtl_0_rxp[0]}]
set_property PACKAGE_PIN AC2 [get_ports {pcie_7x_mgt_rtl_0_rxp[1]}]
set_property PACKAGE_PIN AB4 [get_ports {pcie_7x_mgt_rtl_0_rxp[2]}]
set_property PACKAGE_PIN AA2 [get_ports {pcie_7x_mgt_rtl_0_rxp[3]}]
set_property PACKAGE_PIN T4 [get_ports {pcie_7x_mgt_rtl_1_rxp[0]}]
set_property PACKAGE_PIN R2 [get_ports {pcie_7x_mgt_rtl_1_rxp[1]}]
set_property PACKAGE_PIN P4 [get_ports {pcie_7x_mgt_rtl_1_rxp[2]}]
set_property PACKAGE_PIN N2 [get_ports {pcie_7x_mgt_rtl_1_rxp[3]}]
